# Generated by Django 2.1.1 on 2018-12-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181202_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choicestatus',
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '대기중'), (1, '수락'), (2, '거절')], default=0),
        ),
    ]
