# Generated by Django 2.1.1 on 2018-12-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181203_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='text',
            field=models.CharField(default='/출근 -2', max_length=10),
            preserve_default=False,
        ),
    ]
