# Generated by Django 2.1.1 on 2018-12-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_timelog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='text2break',
            field=models.IntegerField(default=-2),
            preserve_default=False,
        ),
    ]
