# Generated by Django 2.1.1 on 2018-12-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_timelog_text2break'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='text2break',
            field=models.IntegerField(null=True),
        ),
    ]
