# Generated by Django 2.1.1 on 2018-12-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181204_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='text2break',
        ),
    ]
