# Generated by Django 2.1.1 on 2018-12-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181206_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='writter_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
