# Generated by Django 2.1.1 on 2018-12-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_writter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='writter_id',
            field=models.CharField(max_length=10),
        ),
    ]
