# Generated by Django 2.1.1 on 2018-12-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181206_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='half_day_off',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
