# Generated by Django 2.1.1 on 2018-12-06 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20181206_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='timelog',
            name='breaktime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeinfo',
            name='timelog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Timelog'),
        ),
    ]
