# Generated by Django 2.1.1 on 2018-12-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20181210_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='writter_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
