# Generated by Django 2.1.1 on 2018-12-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0021_auto_20181211_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='UpdateRequest',
        ),
    ]
